### ISSUE TITLE
Bug if object already exist in an other group

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPack#4]
![image](https://cloud.githubusercontent.com/assets/5374935/15220945/a6ffbf12-1869-11e6-9eb7-507733600cef.png)

if a component already exist in an other group, it's not imported, instead it create a folder with the name of the component.

**Comment by fgasnier71** [comment]
Now checking if component is already installed. If it is already installed, OK button handler should be disabled!,
